[package]
name = "wasm-src-test1"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"
web-sys = { version = "0.3", features = [
    "ImageData",
    "console",
] }

[profile.release]
opt-level = 3
lto = true